# Generated by Django 4.0.2 on 2022-03-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_question_votor_alter_question_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='votor',
            new_name='voter',
        ),
    ]
